{
 "title": "Restauranty - Stakeholders",
 "tags": [ "restauranty" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "users_total" }
   ]
  },
  {
   "title": "Items in menu",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "items_total" }
   ]
  },
  {
   "title": "Active coupons",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "expr": "coupons_total" }
   ]
  },
  {
   "title": "Total Campains",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "campaigns_total" }
   ]
  },
  {
   "title": "Requests per service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_overall_total{namespace=\"restauranty\"}[5m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Errors (5xx/500) per service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"restauranty\", statusCode=~\"5..\"}[5m])) by (job, route)",
     "legendFormat": "{{job}} {{route}}"
    }
   ]
  }
 ]
}