apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: discounts-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: discounts-deployment
  minReplicas: {{ .Values.discounts.hpa.minReplicas }}
  maxReplicas: {{ .Values.discounts.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.discounts.hpa.targetCPUUtilizationPercentage }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 0
