apiVersion: v1
kind: Service
metadata:
  name: items-service
  labels:
    app: items
spec:
  selector:
    app: items
  ports:
    - name: http    
      port: {{ .Values.items.port }}
      targetPort: {{ .Values.items.port }}
      protocol: TCP
  type: ClusterIP
