kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: restauranty
  name: account-restauranty-manager-gxpft

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: restauranty
  name: role-restauranty-manager-gxpft
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["chaos-mesh.org"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-restauranty-manager-gxpft
  namespace: restauranty
subjects:
- kind: ServiceAccount
  name: account-restauranty-manager-gxpft
  namespace: restauranty
roleRef:
  kind: Role
  name: role-restauranty-manager-gxpft
  apiGroup: rbac.authorization.k8s.io